src/Dlighthouse/urls.py
from django.conf.urls.defaults import *
from Dlighthouse import settings


### Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

### To enable dajaxice
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

### Straight to template
from django.views.generic import TemplateView


urlpatterns = patterns('',
    ### Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    ### to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    ### For dojango
    (r'^dojango/', include('dojango.urls')),

    ### For Haystack
    #(r'^search/', include('haystack.urls')),
    
    
    ###  For dajaxice
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    ### Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    ### Use the files in the media directory:
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    
    ### Use the files in the templates dirctory
    (r'^templates/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.TEMPLATE_ROOT}),  
    
    ### Go to the login page
    url(r'^$', 'django.contrib.auth.views.login', name="login"),
    url(r'^login/$', 'django.contrib.auth.views.login', name="login"),

    ### Go to home page
    url(r'^index/$', TemplateView.as_view(template_name='home.html'), name="home"),
    url(r'^home/$', TemplateView.as_view(template_name='home.html'), name="home"),
    
    ### Link registration/backends/default/urls.py for normal account registration:
    #(r'^accounts/', include('registration.backends.default.urls')),
    
    ### Link emailRegistartion/urls.py to use email as username:
    (r'^accounts/', include('emailRegistration.urls')),

    ### Link blog/urls.py for blog:
    (r'^blog/', include('blog.urls')),

    ### Link forum/urls.py for blog:
    (r'^forum/', include('forum.urls')),
    
    ###----------------- for LAPACK -----------------------###
    ### for LAPACK routines -- link lighthouse/urls/lapack_*.py:
    url(r'^lapack_le/', include('lighthouse.urls.lapack_le')),
    url(r'^lapack_eigen/', include('lighthouse.urls.lapack_eigen')),
    url(r'^lapack_svd/', include('lighthouse.urls.lapack_svd')),
    url(r'^lapack_sylvester/', include('lighthouse.urls.lapack_sylvester')),
    url(r'^lapack_eprob/', include('lighthouse.urls.lapack_eprob')),

    ###----------------- for PETSc -----------------------###
    ### for PETSc routines -- link lighthouse/urls/lapack_*.py:
    url(r'^petsc/', include('lighthouse.urls.petsc_le')),

    ###----------------- for SLEPc -----------------------###
    ### for SLEPc routines -- link lighthouse/urls/lapack_*.py:
    url(r'^slepc_eprob/', include('lighthouse.urls.slepc_eprob')),

    ###----------------- for BTO script ------------------###
    ### ###
    url(r'^btoscript/', include('lighthouse.urls.btoscript'))

)

urlpatterns += staticfiles_urlpatterns()

src/Dlighthouse/lighthouse/forms/lapack_le.py
from django import forms
from django.db.models import get_model





### ---------------- for guided search ---------------- ###

Problem_choices = (
	('Combine lapack_le_only solve',					'Solve a system of linear equations only'),
	('Computational lapack_le_factor factorization',			'Factor a matrix'),
	('Computational lapack_le_inverse inverse',				'Invert a matrix'),
	('Computational lapack_le_condition_number condition', 			'Estimate the condition number of a matrix'),
	('Computational lapack_le_equilibrate equilibrate',			'Equilibrate a matrix'),
	('Computational lapack_le_error_bound error',				'Compute forward or backward error bound for the solution to a linear system'),
	('Computational lapack_le_error_bound refine',				'Refine the solution to a linear system'),
	('Driver lapack_le_expert',						'Solve a system of linear equations AND'),
	('Driver lapack_le_expert refine',					'Refine the solution'),
	('Driver lapack_le_expert error',					'Compute forward or backward error bounds for the solution'),
	('Driver lapack_le_expert condition', 					'Estimate the condition number of the matrix'),
	('Driver lapack_le_expert equilibrate',					'Equilibrate a matrix'),
)



class ProblemForm(forms.Form):
	question_prob = forms.MultipleChoiceField(label='Which of the following do you wish to execute?', widget=forms.CheckboxSelectMultiple(), choices=Problem_choices)

	@staticmethod
	def find(answer):
		for item in Problem_choices:
			if answer == item[0]:
				return item[1]




Equation_choices = (
	('original',				'AX = B'),
	('transpose',				'A<sup>T</sup>X = B'),
	('Hermitian_trans',			'A<sup>H</sup>X = B'),
)


class EquationForm(forms.Form):
	question_equa = forms.ChoiceField(label='What form of the linear system do you want to solve?', widget=forms.RadioSelect(), choices=Equation_choices)




#class FactorForm(forms.Form):
#	question_fact = forms.ChoiceField(label='Is your matrix factored?', choices=([('y','yes'), ('n','no')]), widget=forms.RadioSelect(), initial = dict())





class ComplexForm(forms.Form):
	question_comp = forms.ChoiceField(label='Are there complex numbers in your matrix?', choices=([('y','yes'), ('n','no'),('what', 'I don\'t know'),]), widget=forms.RadioSelect(attrs={'onclick': "disableComplex(request.session['Complex_initial'])"}), initial = dict())





class MatrixTypeForm(forms.Form):
	question_type = forms.ChoiceField(label='What is the type of your matrix?', choices=[], widget=forms.RadioSelect())
	def __init__(self, request, *args, **kwargs):
		super(MatrixTypeForm, self).__init__(*args, **kwargs)
		self.fields['question_type'].choices = request.session['Routines'].values_list('matrixType', 'matrixType').distinct()
		##--- display full names for semidefinite, SPD and HPD ---##
		for i, item in enumerate(self.fields['question_type'].choices):
			if 'SPD' in item:
				self.fields['question_type'].choices[i] = (u'SPD', u'real symmetric positive definite (SPD)')
			elif 'HPD' in item:
				self.fields['question_type'].choices[i] = (u'HPD', u'complex Hermitian positive definite (HPD)')
			elif 'SPsD' in item:
				self.fields['question_type'].choices[i] = (u'SPsD', u'real symmetric positive semidefinite (SPsD)')
			elif 'HPsD' in item:
				self.fields['question_type'].choices[i] = (u'HPsD', u'complex Hermitian positive semidefinite (HPsD)')
		##--- order choices by string length ---##
		self.fields['question_type'].choices.sort(key=lambda k:len(k[1]))
		if len(self.fields['question_type'].choices) == 1:
			self.fields['question_type'].initial = self.fields['question_type'].choices[0][1]




class StorageForm(forms.Form):
	question_stor = forms.ChoiceField(label='How is your matrix stored?', choices=[], widget=forms.RadioSelect())
	def __init__(self, request, *args, **kwargs):
		super(StorageForm, self).__init__(*args, **kwargs)
		self.fields['question_stor'].choices = request.session['Routines'].values_list('storageType', 'storageType').distinct()
		##--- display full name for RFP ---##
		for i, item in enumerate(self.fields['question_stor'].choices):
			if 'RFP' in item:
				self.fields['question_stor'].choices[i] = (u'RFP', u'rectangular full packed (RFP)')
		self.fields['question_stor'].choices.sort(key=lambda k:len(k[1]))
		if len(self.fields['question_stor'].choices) == 1:
			self.fields['question_stor'].initial = self.fields['question_stor'].choices[0][1]




class PrecisionForm(forms.Form):
	question_prec = forms.ChoiceField(label='Would you like to use single or double precision?', choices=([('s','single'), ('d','double'), ('what', 'I don\'t know'),]), widget=forms.RadioSelect())










### ---------------- for advanced search ---------------- ###
Advanced_choices = (
	('Computational lapack_le_computationalForm', 'Computational Routines'),
	('Driver lapack_le_simpleForm', 'Simple Driver Routines'),
	('Driver lapack_le_expertForm', 'Expert Driver Routines'),
)

class AdvancedForm(forms.Form):
	advanced = forms.MultipleChoiceField(label='Which of the following routine categories would you like to search?', required=True, widget=forms.CheckboxSelectMultiple(), choices=Advanced_choices)

	@staticmethod
	def find(answer):
		for item in Advanced_choices:
			if answer == item[0]:
				return item[1]




###--------------- Linear Equation Computational Forms ------------------###
Function_choices = (
	('factorization',		'factor a matrix (PA = LU)'),
	('inverse',			'invert a matrix'),
	('condition', 			'estimate the condition number of a matrix'),
	('equilibrate',			'equilibrate a matrix'),
	('solve',			'solve a linear system'),
	('error',			'compute forward or backward error bounds for the solution to a linear system'),
	('refine',			'refine the solution to a linear system'),
)

Complex_choices = (
	('yes',				'yes'),
	('no',				'no'),
)

MatrixTypeComputational_choices = (
	('general',			'general'),
	('Hermitian',			'Hermitian'),
	('symmetric',			'symmetric'),
	('triangular',			'triangular'),
	('SPD',				'real symmetric positive definite (SPD)'),
	('HPD',				'complex Hermitian positive definite (HPD)'),	
	('SPsD', 			'real symmetric positive semidefinite (SPsD)'),
	('HPsD', 			'complex Hermitian positive semidefinite (HPsD)'),
)

MatrixType_choices = (
	('general',			'general'),
	('Hermitian',			'Hermitian'),
	('symmetric',			'symmetric'),
	('SPD',				'real symmetric positive definite (SPD)'),	
	('HPD',				'complex Hermitian positive definite (HPD)'),		
)

StorageTypeComputational_choices = (
	('full',			'full'),
	('band',			'band'),
	('packed',			'packed'),
	('tridiagonal',			'tridiagonal'),
	('RFP',				'rectangular full packed (RFP)'),
)
	
StorageType_choices = (
	('full',			'full'),
	('band',			'band'),
	('packed',			'packed'),
	('tridiagonal',			'tridiagonal'),
)

Precision_choices = (
	('single',			'single'),
	('double',			'double'),
)




class lapack_le_computationalForm(forms.Form):
	Description = 'Perform various computational tasks'
	lapack_le_computationalFunction = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=Function_choices)
	lapack_le_computationalComplex = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=Complex_choices)
	lapack_le_computationalMatrixType = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=MatrixTypeComputational_choices)
	lapack_le_computationalStorageType = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=StorageTypeComputational_choices)
	lapack_le_computationalPrecision = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=Precision_choices)

	@staticmethod
	def find(answer):
		for item in Function_choices:
			if answer == item[0]:
				return item[1]




###--------------- Linear Equation Simple Driver Forms ------------------###
class lapack_le_simpleForm(forms.Form):
	Description = 'Solve a system of linear equations'
	lapack_le_simpleFunction = forms.MultipleChoiceField(choices=([('solve','AX=B')]), widget=forms.CheckboxSelectMultiple(), initial=['solve'])
	lapack_le_simpleComplex = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=Complex_choices)
	lapack_le_simpleMatrixType = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=MatrixType_choices)
	lapack_le_simpleStorageType = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=StorageType_choices)
	lapack_le_simplePrecision = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=Precision_choices)

	@staticmethod
	def find(answer):
		return 'AX=B'





###--------------- Linear Equation Expert Driver Forms ------------------###
ExpertDriverEquation_choices = (
	('solve',					'AX = B'),
	('transpose',					'A<sup>T</sup>X = B'),
	('Hermitian_trans',				'A<sup>H</sup>X = B'),
)

ExpertDriverFunction_choices = (
	('condition',					'estimate the matrix condition number'),
	('error',					'compute error bounds for the solution'),
	('refine',					'refine the solution'),
	('equilibrate',					'equilibrate the matrix'),
)	

class lapack_le_expertForm(forms.Form):
	Description = 'Solve a system of linear equations AND perform various computational routines'
	lapack_le_expertEquation = forms.MultipleChoiceField(label='Equations:', widget=forms.CheckboxSelectMultiple(), choices=ExpertDriverEquation_choices)
	lapack_le_expertFunction = forms.MultipleChoiceField(label='Tasks:', widget=forms.CheckboxSelectMultiple(), choices=ExpertDriverFunction_choices)
	lapack_le_expertComplex = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=Complex_choices)	
	lapack_le_expertMatrixType = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=MatrixType_choices)	
	lapack_le_expertStorageType = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=StorageType_choices)	
	lapack_le_expertPrecision = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=Precision_choices)

	@staticmethod
	def find_equation(answer):

src/Dlighthouse/templates/Search/complex.html
{% extends "dojango/base.html" %}


{% block dojango_content_simpleSearch %}
<div id="title-div">
  <table id="icon-table">
    <tr>
      <td id="icon-cell">
        <img src="{{ MEDIA_URL }}Images/guidedSearch.png" width="32" height="32"/>
      </td>   
      <td id="title-cell">
        Guided Search
      </td>
    </tr>
  </table>  
</div>
<br>


<!-- ### Question 1 answered. ###-->
<tr>
  <th>
    <label for="id_question_prob">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Which of the following functions do you wish to execute?</b>
    </label>
  </th>
  {% for item in query_prob %} 
  <ul style="margin-left: 0; padding-left: 20px;">
      <li style="list-style-type: none; padding-left:-10px;">
        <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
        {{ item.1 }}
      </li>
  </ul>
  {% endfor %}
</tr>



<!-- ### Questions 2, 3, and 4 answered. ###-->
{% if query_equa != 0 %} 
<tr>
  <th>
    <label for="id_question_equa">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> What form of the linear system do you want to solve?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
    <li style="list-style-type: none; padding-left:-10px;">
      <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
      {{ query_equa|safe }}
    </li>
</ul>
</tr>

<tr>
  <th>
    <label for="id_question_fact">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Is your matrix factorized?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
    <li style="list-style-type: none; padding-left:-10px;">
      <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
      {{ query_fact }}
  </li>
</ul>
</tr>

<tr>
  <th>
    <label for="id_question_comp">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Are there complex numbers in your matrix?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
    <li style="list-style-type: none; padding-left:-10px;">
      <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
      {{ query_comp }}
    </li>
</ul>
</tr>




<!-- ### OR Questions 2 answered. ###-->
{% else %}
<tr>
  <th>
    <label for="id_question_comp">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Are there complex numbers in your matrix?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
    <li style="list-style-type: none; padding-left:-10px;">
      <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
      {{ query_comp }}
    </li>
</ul>
</tr>
{% endif %}





<!-- ### Question 3/5: What is the type of your matrix? ###-->
<form action="/search/guided/problem_complex_matrixtype/" name="frmType" method="post">
  	{% csrf_token %}
  <div id="question-div">
    {{ form.as_ul }}    
  </div>
  <br>
    
    

    <div id="button-div">
      <table style="width:100%; margin: 0px auto;">
    <tr style="width:100%;">
      <td style="text-align:left;">       
        <button type="button" name="clear" id="clearButton" title="Clear Search" onmouseover="showTooltip('tooltip', 'Clear Search','#cc0000');" onmouseout="showTooltip('tooltip','');" onclick="return show_confirm()">
            <img src="{{ MEDIA_URL }}Images/clear.png" width="16" height="16"/> 
        </button>       
      </td>     
      <td style="text-align:center;">
        <div id="tooltip"></div>
      </td>
      <td style="text-align:right;">
        <button type="submit" name="Submit" id="submitButton" title="Submit Answer" onmouseover="showTooltip('tooltip', 'Submit', '#009900');" onmouseout="showTooltip('tooltip','');" onclick="return checkRadios();">
            <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="16" height="16"/>
        </button >
      </td>
    </tr>
      </table>
  </div>
</form>


{% endblock %}
<!-- ########################################################################################################## -->




<!-- ########### Simple search result: ###########-->
{% block dojango_content_search_result %}
{% include "search/simpleResult.html" %}
{% endblock %}

<!-- ########### Advanced search questions: ###########-->

{% block dojango_content_advancedSearch %}
{% include "search/advancedSearch.html" %}
{% endblock %}


<!-- ########### Keyword search: ###########-->
{% block dojango_content_keywordSearch %}
{% include "search/keywordSearch.html" %}
{% endblock %}


<!-- ########### Selected routines: ###########-->
{% block dojango_content_selected_routines %}
{% include "search/selectedRoutines.html" %}
{% endblock %}


<!-- ########### Code Template: ###########-->
{% block dojango_content_code_template %}
{% include "search/codeTemplate.html" %}
{% endblock %}

<!-- ########### Script Area: ###########-->
{% block dojango_content_script %}
{% include "search/script.html" %}
{% endblock %}

src/Dlighthouse/templates/Search/precision.html
{% extends "dojango/base.html" %}


{% block dojango_content_simpleSearch %}
<div id="title-div">
  <table id="icon-table">
    <tr>
      <td id="icon-cell">
        <img src="{{ MEDIA_URL }}Images/guidedSearch.png" width="32" height="32"/>
      </td>   
      <td id="title-cell">
        Guided Search
      </td>
    </tr>
  </table>  
</div>
<br>


<!-- ########### All questions answered: ###########-->
<tr>
  <th>
    <label for="id_question_prob">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Which of the following functions do you wish to execute?</b>
    </label>
  </th>
{% for item in query_prob %} 
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ item.1 }}
  </li>
</ul>
  {% endfor %}
</tr>





{% if query_equa != 0 %} 
<tr>
  <th>
    <label for="id_question_equa">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> What form of the linear system do you want to solve?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_equa|safe }}
  </li>
</ul>
</tr>


<tr>
  <th>
    <label for="id_question_fact">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Is your matrix factorized?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_fact }}
  </li>
</ul>
</tr>


<tr>
  <th>
    <label for="id_question_comp">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Are there complex numbers in your matrix?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_comp }}
  </li>
</ul>
</tr>


<tr>
  <th>
    <label for="id_question_zero">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> What is the type of your matrix?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_type }}
  </li>
</ul>
</tr>


<tr>
  <th>
    <label for="id_question_stor">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> How is your matrix stored?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_stor }}
  </li>
</ul>
</tr>


<tr>
  <th>
    <label for="id_question_prec">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Would you like to use single or double precision?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_prec }}
  </li>
</ul>
</tr>






{% else %}

<tr>
  <th>
    <label for="id_question_comp">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Are there complex numbers in your matrix?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_comp }}
  </li>
</ul>

</tr>


<tr>
  <th>
    <label for="id_question_zero">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> What is the type of your matrix?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_type }}
  </li>
</ul>
</tr>


<tr>
  <th>
    <label for="id_question_stor">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> How is your matrix stored?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_stor }}
  </li>
</ul>
</tr>


<tr>
  <th>
    <label for="id_question_prec">
      <img src="{{ MEDIA_URL }}Images/arrow.png" width="8" height="8"/>
      <b> Would you like to use single or double precision?</b>
    </label>
  </th>
<ul style="margin-left: 0; padding-left: 20px;">
  <li style="list-style-type: none; padding-left:-10px;">
    <img src="{{ MEDIA_URL }}Images/dialog-ok-4.png" width="8" height="8"/> 
    {{ query_prec }}
  </li>
</ul>
</tr>
{% endif %}



<div id="button-div">
  <table style="width:100%; margin: 0px auto;">
    <tr style="width:100%;">
      <td style="text-align:left">
	      <img src="{{ MEDIA_URL }}Images/face-smile-2.png" width="20" height="20"/>
      </td>
      <td style="text-align:left; color: #0c387e;">
	      <b>End of guided search! Check out the result.</b>
      </td>
      <td style="text-align:right; width: 75px;">
        <div id="tooltip"></div>
      </td>       
      <td style="text-align:right">
        <button type="button" name="clear" id="clearButton" title="Clear Search" onmouseover="showTooltip('tooltip', 'Clear Search','#cc0000');" onmouseout="showTooltip('tooltip','');" onclick="return show_confirm()">
              <img src="{{ MEDIA_URL }}Images/clear.png" width="16" height="16"/> 
        </button>      
      </td>
    </tr>
  </table>
</div>

{% endblock %}
<!-- ########################################################################################################## -->




<!-- ########### Simple search result: ###########-->
{% block dojango_content_search_result %}
{% include "search/simpleResult.html" %}
{% endblock %}

<!-- ########### Advanced search questions: ###########-->

{% block dojango_content_advancedSearch %}
{% include "search/advancedSearch.html" %}
{% endblock %}


<!-- ########### Keyword search: ###########-->
{% block dojango_content_keywordSearch %}
{% include "search/keywordSearch.html" %}
{% endblock %}


<!-- ########### Selected routines: ###########-->
{% block dojango_content_selected_routines %}
{% include "search/selectedRoutines.html" %}
{% endblock %}


<!-- ########### Code Template: ###########-->
{% block dojango_content_code_template %}
{% include "search/codeTemplate.html" %}
{% endblock %}

<!-- ########### Script Area: ###########-->
{% block dojango_content_script %}
{% include "search/script.html" %}
{% endblock %}