src/lighthouseProject/blog/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

### --- when using generic views --- ###
from django.views.generic import ListView, DetailView
from blog.models import Post

from django.contrib.syndication.views import Feed

class BlogFeed(Feed):
    title = "MySite -- using generic views"
    description = "Some ramblings of mine"
    link = "/blog/feed"
    
    def items(self):
        return Post.objects.all().order_by("-created")[:2]
    def item_title(self, item):
        return item.title
    def item_description(self, item):
        return item.body    
    def item_link(self, item):
        return u"/blog/%d" % item.id




urlpatterns = patterns('blog.views',
### --- The following lines use blog.views --- ###
    url(r'^$', "main", name='blogindex'),
    url(r"^(\d+)/$", "post", name="post"),
    url(r"^add_comment/(\d+)/$", "add_comment"),
    url(r"^month/(\d+)/(\d+)/$", "month"),
    url(r"^delete_comment/(\d+)/$", "delete_comment"),
    url(r"^delete_comment/(\d+)/(\d+)/$", "delete_comment"),
    url(r"^search/$", "MySearchView"),
    
    
### --- The following lines use generic views --- ###
    #url(r'^$', ListView.as_view(
    #    queryset = Post.objects.all().order_by("-created")[:2],
    #    template_name = "blog.html")),
    #url(r'^(?P<pk>\d+)$', DetailView.as_view(
    #    model = Post,
    #    template_name = "post.html")),
    #url(r'^archives/$', ListView.as_view(
    #    queryset = Post.objects.all().order_by("-created"),
    #    template_name = "archives.html")),
    #url(r'^tag/(?P<tag>\w+)$', 'tagpage'),
    #url(r'^feed/$', BlogFeed()),
)

src/lighthouseProject/forum/urls.py
from django.conf.urls.defaults import *
from django.conf import settings


urlpatterns = patterns('forum.views',
### --- The following lines use forum.views --- ###
    url(r"^$", "main", name="forumList"),
    url(r"^forum/(\d+)/$", "forum", name="forum"),
    url(r"^thread/(\d+)/$", "thread", name="thread"),
    
    url(r"^post/(new_thread|reply)/(\d+)/$", "post", name="forumPost"),
    url(r"^reply/(\d+)/$", "reply", name="reply"),
    url(r"^new_thread/(\d+)/$", "new_thread", name="new_thread"),
    
    url(r"^search/$", "MyForumSearchView", name="forumSearch"),
)

src/lighthouseProject/lighthouseProject/urls.py
from django.conf.urls import patterns, include, url

### Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


### Configure dajaxice url
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

### static files
from django.conf import settings
from django.conf.urls.static import static

### Straight to template
from django.views.generic import TemplateView


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lighthouseProject.views.home', name='home'),
    # url(r'^lighthouseProject/', include('lighthouseProject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    ### Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    ### for dajaxcie
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    
    ### for dojango
    (r'^dojango/', include('dojango.urls')),

    #### Use the files in the media directory:
    #(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    #
    #### Use the files in the templates dirctory
    #(r'^templates/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.TEMPLATE_ROOT}),  
    
    ### Go to the login page
    url(r'^$', 'django.contrib.auth.views.login', name="login"),
    url(r'^login/$', 'django.contrib.auth.views.login', name="login"),

    ### Go to home page
    url(r'^index/$', TemplateView.as_view(template_name='home.html'), name="home"),
    url(r'^home/$', TemplateView.as_view(template_name='home.html'), name="home"),
    
    ### Link registration/backends/default/urls.py for normal account registration:
    #(r'^accounts/', include('registration.backends.default.urls')),
    
    ### Link emailRegistartion/urls.py to use email as username:
    (r'^accounts/', include('emailRegistration.urls')),

    ### Link blog/urls.py for blog:
    (r'^blog/', include('blog.urls')),

    ### Link forum/urls.py for blog:
    (r'^forum/', include('forum.urls')),
    
    
    ###----------------- for LAPACK -----------------------###
    #url(r'^lapack_le/', include('lighthouse.urls.lapack_le')),
    url(r'^lapack_eigen/', include('lighthouse.urls.lapack_eigen')),
    url(r'^lapack_svd/', include('lighthouse.urls.lapack_svd')),
    url(r'^lapack_sylvester/', include('lighthouse.urls.lapack_sylvester')),

    ###----------------- for PETSc -----------------------###
    #url(r'^petsc/', include('lighthouse.urls.petsc_le')),

    ###----------------- for SLEPc -----------------------###
    #url(r'^slepc_eprob/', include('lighthouse.urls.slepc_eprob')),

    ###----------------- for BTO script ------------------###
    ### ###
    #url(r'^btoscript/', include('lighthouse.urls.btoscript'))
    
    
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/lighthouseProject/forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.forms import ModelForm
from string import join
from lighthouseProject.settings import MEDIA_ROOT

class Forum(models.Model):
    title = models.CharField(max_length=60)
    
    def __unicode__(self):
        return self.title
    
    def num_threads(self):
        return self.thread_set.count()
    
    def num_replies(self):
        return sum([t.num_posts() for t in self.thread_set.all()])-self.thread_set.count()

    def last_post(self):
        if self.thread_set.count():
            last = None
            for t in self.thread_set.all():
                l = t.last_post()
                if l:
                    if not last: last = l
                    elif l.created > last.created: last = l
            return last



class Thread(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    body = models.TextField(max_length=10000)
    forum = models.ForeignKey(Forum)

    def __unicode__(self):
        return unicode(self.creator) + " - " + self.title
    
    def num_posts(self):
        return self.post_set.count()

    def num_replies(self):
        return self.post_set.count() - 1

    def last_post(self):
        if self.post_set.count():
            return self.post_set.order_by("created")[0]
        
        

class Post(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    thread = models.ForeignKey(Thread)
    body = models.TextField(max_length=10000)

    def __unicode__(self):
        return u"%s - %s - %s" % (self.creator, self.thread, self.title)

    def short(self):
        return u"%s - %s" % (self.title, self.creator)
    
    def short_time(self):
        return u"%s" % (self.created.strftime("%b %d, %I:%M %p"))
    short.allow_tags = True
    
    
    
""" Forms """
    
class ThreadForm(ModelForm):
    class Meta:
        model = Thread
        exclude = ["forum", "creator"]
        
        
class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ["thread", "creator"]

src/lighthouseProject/forum/views.py
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from django.core.context_processors import csrf
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from lighthouseProject.settings import MEDIA_ROOT, MEDIA_URL
from forum.models import Forum, Thread, Post, ThreadForm, PostForm

from haystack.views import SearchView
from haystack.query import SearchQuerySet
from haystack.forms import ModelSearchForm




def main(request):
    """Main listing."""
    forums = Forum.objects.all()
    d = {"forums": forums, "user": request.user, "searchForm": ModelSearchForm()}
    return render_to_response("forum/list.html", d)



def mk_paginator(request, items, num_items):
    """Create and return a paginator."""
    paginator = Paginator(items, num_items)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        items = paginator.page(page)
    except (InvalidPage, EmptyPage):
        items = paginator.page(paginator.num_pages)
    return items



def add_csrf(request, ** kwargs):
    d = dict(user=request.user, ** kwargs)
    d.update(csrf(request))
    return d


def forum(request, pk):
    """Listing of threads in a forum."""
    threads = Thread.objects.filter(forum=pk).order_by("-created")
    threads = mk_paginator(request, threads, 20)
    return render_to_response("forum/forum.html", add_csrf(request, threads=threads, pk=pk, searchForm= ModelSearchForm()))


def thread(request, pk):
    """Listing of posts in a thread. The first post is always the thread post."""
    thread = Post.objects.filter(thread=pk).order_by("created")[0]
    posts = Post.objects.filter(thread=pk).order_by("created")[1:]
    posts = mk_paginator(request, posts, 15)
    title = Thread.objects.get(pk=pk).title
    
    """creates the paginator with 2 items per page."""
    #paginator = Paginator(posts, 3)
    #
    #try: page = int(request.GET.get("page", '1'))
    #except ValueError: page = 1
    #
    #try:
    #    posts = paginator.page(page)
    #except (InvalidPage, EmptyPage):
    #    posts = paginator.page(paginator.num_pages)
        
    return render_to_response("forum/thread.html", add_csrf(request, thread=thread, posts=posts, pk=pk,
        title=title, searchForm= ModelSearchForm()))


def post(request, ptype, pk):
    """Display a post form."""
    action = reverse("%s" % ptype, args=[pk])
    if ptype == "new_thread":
        title = "Start New Topic"
        subject = ''
        form = ThreadForm()
    elif ptype == "reply":
        title = "Reply to " + "\""+ Thread.objects.get(pk=pk).title + "\""
        subject = "Re: " + Thread.objects.get(pk=pk).title
        form = PostForm(initial={'title': subject})
    return render_to_response("forum/post.html", add_csrf(request, subject=subject,
        action=action, title=title, form=form, searchForm= ModelSearchForm()))


def new_thread(request, pk):
    """Start a new thread."""
    if request.method == 'POST':
        form = ThreadForm(request.POST)
        if form.is_valid():
            p = form.cleaned_data
            forum = Forum.objects.get(pk=pk)
            """ save the thread in table Thread"""
            thread = Thread.objects.create(forum=forum, title=p["title"], creator=request.user)
            """ save the thread in table Post, too """
            Post.objects.create(thread=thread, title=p["title"], body=p["body"], creator=request.user)
        return HttpResponseRedirect(reverse("forum", args=[pk]))




def reply(request, pk):
    """Reply to a thread --> new post."""
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            p = form.cleaned_data
            thread = Thread.objects.get(pk=pk)
            post = Post.objects.create(thread=thread, title=p["title"], body=p["body"], creator=request.user)
        return HttpResponseRedirect(reverse("thread", args=[pk]) + "?page=last")



""" perform haystack search """
def MyForumSearchView(request):
    form = ModelSearchForm(request.GET) # A form bound to the GET data
    if form.is_valid(): # All validation rules pass
        sqs = SearchQuerySet().models(Post)
        search_view = SearchView(template = "forum/forum_search.html", searchqueryset=sqs)
        return search_view(request)

src/lighthouseProject/forum/templates/forum/fbase.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{% block title %}Lighthouse Forum{% endblock %}</title>
    <link rel="shortcut icon" href="/media/Images/favicon.png"/>
    <link rel="stylesheet" type="text/css" href="/static/forumstyle.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/dojo/1.6/dijit/themes/claro/claro.css"/>
    <script src="http://ajax.googleapis.com/ajax/libs/dojo/1.6/dojo/dojo.xd.js"
        djConfig="parseOnLoad: true">
    </script>
    <script type="text/javascript">
	{% include "forum/js_functions.js" %}
    </script>
</head>

<body>
	<!-- "main" BorderContainer just contains page title and another BorderContainer -->
        <div style="height:57px; padding-left:8px; border-top:6px; border-left: 1px; border-right: 1px; border-bottom:1px; border-style:solid; background:#fff; border-color:#c9dcfa;">

		<img src="/media/Images/forum_header.png"/>
		<div style="float:right; padding-top: 13px; padding-right: 5px; font:11.5px sans-serif;">
			{% if user.is_authenticated %}                            
				<div style="text-align:right; color:#808080;">
					<table>
						<tr>
							<td>Welcome, {{ user.username }}!</td>
						</tr>
						<tr>
						<!--<a href="/accounts/logout/"><img src="{{ MEDIA_URL }}Images/logout.png"/></a>-->        
							<td>My Account &nbsp;&nbsp; | &nbsp;&nbsp;
							    <a style="text-decoration: none;" href="/accounts/logout/">Logout</a>
							</td>
						</tr>
					</table>        
				</div>
			{% else %}
				<div>
					<table>
						<tr>
							<td>
								<a href="/accounts/logout/"><img src="/media/Images/logout.png"/></a>
							</td>          
							<td>
								<a style="text-decoration: none; color:#000;" href="/accounts/logout/">logout</a>
							</td>
						</tr>
					</table>        
				</div>                                
			{% endif %}
		</div>
	</div>		 
    <div id="header">	
	{% block nav-global %}
	<ul>
	    <li><a href="/index/">Home</a></li>
	    <li><a href="{% url blogindex %}">Blog</a></li>
	    {% if user.is_staff %}
	    <li><a href="{% url admin:index %}">Admin</a></li>
	    <li><a href="{% url admin:blog_post_add %}">Add post</a></li>
	    <li><a href="{% url admin:forum_forum_add %}">Add forum</a></li>
	    {% endif %}
	</ul>
	<div id="layoutdims">
	    <form method="get" action="{% url forumSearch %}">
	    <table align="center">
		<tr>
			<td style="text-align:right;">Search</td>
			<td style="text-align:center;"><input style="width: 250px; padding: 3px" type="text" name="q" id="id_q" /></td>
			<td style="text-align:left;"><input type="submit" value="Search" onclick="return searchbutcheck_onclick()"></td>
		</tr>
	    </table>
	    </form>
	</div>
	{% endblock %}
    </div>
    <div class="colmask rightmenu">
	    <div class="colleft">
		    <div class="col1">
			    <!-- Column 1 start -->
			    {% block content %}{% endblock %}
			    <!-- Column 1 end -->
		    </div>
		    <div class="col2">
			    <!-- Column 2 start -->
			    {% block sidebar %}{% endblock %}
			    <!-- Column 2 end -->
		    </div>
	    </div>
    </div>
    <div id="footer">
	    {% if user.is_staff %}
		<p>{{ user }}</p>
	    {% else %}
		<p>Lighthouse is awesome!</p>
	    {% endif %}
    </div>

</body>
</html>

src/lighthouseProject/forum/templates/forum/forum.html
{% extends "forum/fbase.html" %}

{% block content %}
</br></br>
<form action="{% url forumPost 'new_thread' pk %}" method="post">
    {% csrf_token %}
    <button>
        Start New Topic
    </button>
</form>
<div>
    <table id="hor-zebra", border="0">
        <thead>
            <tr>
                <th scope="col">Topics</th>
                <th scope="col">Replies</th>
                <th scope="col">Last post</th>
            </tr>
        </thead>
        <tbody>
            {% for thread in threads.object_list %}
            <tr class="{% if forloop.counter|divisibleby:2 %}even{% endif %}">
                <td>
                    <div class="title">
                        <a style="text-decoration: none" href="{% url thread thread.pk %}">{{ thread.title }}</a>
                    </div>
                </td>
                <td>
                    {{ thread.num_replies }}
                </td>
                <td >
                    {{ thread.last_post.short }}</br>
                    <span style="font-family:verdana;color:grey;font-size:10px;">{{ thread.last_post.short_time }}</span>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<!-- Next/Prev page links  -->
{% if threads.object_list and threads.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if threads.has_previous %}
            <a href= "?page={{ threads.previous_page_number }}">previous &lt;&lt; </a>
        {% endif %}

        <span class="current">
            &nbsp;Page {{ threads.number }} of {{ threads.paginator.num_pages }}
        </span>

        {% if threads.has_next %}
            <a href="?page={{ threads.next_page_number }}"> &gt;&gt; next</a>
        {% endif %}
    </span>
</div>
{% endif %}

<form action="{% url forumPost 'new_thread' pk %}" method="post">
    {% csrf_token %}
    <button>
        Start New Topic
    </button>
</form>
</br>
{% endblock %}

src/lighthouseProject/forum/templates/forum/forum_search.html
{% extends 'forum/fbase.html' %}
{% load highlight %}


{% block content %}
    {% if query %}
        <h3>{{ page.object_list|length }} of {{ page.paginator.count }} results for "<i>{{ request.GET.q }}</i>"
            on page {{ page.number }} of {{ page.paginator.num_pages }}:</h3>
        <ul>
        {% for result in page.object_list %}
            <li><p><a href="/forum/thread/{{ result.object.thread.id }}#{{ result.object.created }}">{{ result.object.title }},</a>
                &nbsp;
                <span style="font-family:verdana;color:grey;font-size:10px;">{{ result.object.created }}</span></p>
            </li>
            
            {% empty %}
                <p>No results found.</p>
        {% endfor %}
        </ul>
    {% endif %}


    {% if page.has_previous or page.has_next %}
        <div>
            {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
            |
            {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
        </div>
    {% endif %}

{% endblock %}

src/lighthouseProject/forum/templates/forum/list.html
{% extends "forum/fbase.html" %}

{% block content %}
<table id="rounded-corner">
    <thead>
        <tr>
            <th scope="col" class="rounded-company">Forum name</th>
            <th scope="col" class="rounded-q1">Threads</th>
            <th scope="col" class="rounded-q2">Replies</th>
        </tr>
    </thead>
    <tbody>
        {% for forum in forums %}
        <tr>
            <td {% if forloop.last %}class="last"{% endif %}>
                <a style="text-decoration: none; color: #134c94;" href="{% url forum forum.pk %}">{{ forum.title }}</a>
            </td>
            <td {% if forloop.last %}class="last"{% endif %}>
                {{ forum.num_threads }}
            </td>
            <td {% if forloop.last %}class="last"{% endif %}>
                {{ forum.num_replies }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td class="rounded-foot-left"></td>
            <td colspan="2" class="rounded-foot-right">&nbsp;</td>
        </tr>
    </tfoot>
</table>
{% endblock %}

src/lighthouseProject/forum/templates/forum/post.html
{% extends "forum/fbase.html" %}

{% block content %}
    <h4>{{ title }}</h4>
    
    <form dojoType="dijit.form.Form" method="post" action="{{ action }}">{% csrf_token %}
        <table border="0" height="80%"  cellspacing="10">
            <!--for starting a new tread (question)-->
            {% if not subject %}
            <tr>
                <th align="left" style="width: 10%">
                    <label for="id_title">Title:</label>
                </th>
                <td align="left">
                    <input id="id_title" type="text" style="width: 99%" name="title" maxlength="60"
                            dojoType="myValidationTextarea" required="true"/>
                </td>
            </tr>
            <!--for creating a new post (reply to a thread)-->
            {% else %}
            <tr>
                <th align="left" style="width: 10%">
                    <label for="id_title">Subject:</label>
                </th>
                <td align="left">
                    <input id="id_title" type="text" style="width: 99%" name="title" value="{{ subject }}" maxlength="60"
                            dojoType="myValidationTextarea" required="true"/>
                </td>
            </tr>
            {% endif %}
            <tr>
                <th align="left">
                    <label for="id_body">Body:</label>
                </th>
            </tr>    
            <tr>
                <td colspan="2" >
                    <textarea id="id_body" name="body" rows="40" cols="70"
                              dojoType="myValidationTextarea" required="true"></textarea>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <button dojoType="dijit.form.Button" type="button" onnclick="JavaScript:history.back();">
                        Cancel
                    </button>
                    <button dojoType="dijit.form.Button" type="submit">
                        Submit
                    </button>
                </td>
            </tr>
        </table>
    </form>

        
{% endblock %}

src/lighthouseProject/forum/templates/forum/thread.html
{% extends "forum/fbase.html" %}

{% block content %}
<div>
    <table id="box-table-a" width=80%>
        <tr>
            <th>
                <p style="text-align:center">
                    {{ thread.title }}</br>
                    <span style="font-family:verdana;color:grey;font-size:10px;" id="{{ thread.created }}">
                        by {{ thread.creator }} | {{ thread.created }}</span>
                </p>
                <div STYLE="font-size: 12px; font-weight:lighter"> {{ thread.body }} </div>
            </th>
        </tr>
        {% for post in posts.object_list %}
        <tr>
            <td>
                {{ post.title }}<br/>
                <span style="font-family:verdana;color:grey;font-size:10px;" id="{{ post.created }}">&nbsp &nbsp &nbsp by {{ post.creator }} | {{ post.created }}</span>
                </br></br>
                {{ post.body }}
            </td>
        </tr>
        {% endfor %}
    </table>
    <table width=80%>
        <tr><td align="right"><a style="text-decoration: none" href="{% url forum.views.post 'reply' pk %}">Reply</a></td></tr>
    </table>
</div>

<!-- Next/Prev page links -->
<!--{% if posts.object_list and posts.paginator.num_pages > 1 %}
<div class="pagination" style="text-align:center;">
    <span class="step-links">
        {% if posts.has_previous %}
            <a style="text-decoration: none" href= "?page={{ posts.previous_page_number }}">older entries &lt;&lt; </a>
        {% endif %}

        <span class="current">
            &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>

        {% if posts.has_next %}
            <a style="text-decoration: none" href="?page={{ posts.next_page_number }}"> &gt;&gt; newer entries</a>
        {% endif %}
    </span>
</div>
{% endif %}-->
<!-- END Next/Prev page links -->

{% endblock %}